-- Database: GLOBALCIG Metadata version: 2 Exported: Mar 9, 2020
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5786_BOMIMPORT" USING 'GCG_5786_BOMIMPORT.mkd' PAGESIZE=16384 (
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0,
 "BOM_PARENT" CHAR(20),
 "ITEMNO" CHAR(4),
 "PART_SOURCE" CHAR(10),
 "PART_CLASS" CHAR(50),
 "PART_TYPE" CHAR(50),
 "WC" CHAR(20),
 "PART" CHAR(17),
 "REV" CHAR(3),
 "CUST_PART" CHAR(50),
 "CUST_REV" CHAR(3),
 "DESCRIPT" VARCHAR(50),
 "PACKAGE" CHAR(50),
 "PIN_COUNT" CHAR(50),
 "MSL" CHAR(50),
 "QTY" CHAR(50),
 "UM" CHAR(2),
 "PURCH_CONV_FACTOR" CHAR(50),
 "PURCH_UM" CHAR(2),
 "REF_DESG" NVARCHAR(4000),
 "MFG" CHAR(50),
 "MPN" CHAR(50),
 "BIN" CHAR(6),
 "STD_COST" CHAR(50),
 "MIN_ORDER_QTY" CHAR(50),
 "ORDER_MULTIPLE" CHAR(50),
 "LEAD_TIME" CHAR(50),
 "PART_PACKAGE" CHAR(50),
 "ROHS_VERSION" CHAR(50),
 "ROHSEXCEPTIONAPPLIES" CHAR(50),
 "ROHSEXCEPTIONS" CHAR(50),
 "REACHCONTAINSSVHC" CHAR(50),
 "REACHCONTAINEDCAS" CHAR(50),
 "REACHSVHCLIMITEXCEEDED" CHAR(50),
 "REACHSVHCLIMITEXCEEDEDCAS" CHAR(50),
 "REACHLISTVER" CHAR(50),
 "CAL65STATUS" CHAR(50),
 "CAPROP65CAS" CHAR(50),
 "NCNR" CHAR(3),
 "RUN_SCRAP" NUMERIC(8,2),
 "CERTS_REQ" CHAR(3),
 "INSP_REQ" CHAR(3),
 "SORT_CODE" CHAR(20) );
-- End Multi-Line Statement
ALTER TABLE "GCG_5786_BOMIMPORT" ADD CONSTRAINT "PK_ID" PRIMARY KEY  ( "ID" ) USING 0;
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
