-- Database: GLOBALCIG Metadata version: 2 Exported: Mar 9, 2020
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5786_MFG" USING 'GCG_5786_MFG.mkd' PAGESIZE=4096 (
 "MFG_CODE" CHAR(23) NOT NULL,
 "MFG_NAME" NVARCHAR(100) );
-- End Multi-Line Statement
ALTER TABLE "GCG_5786_MFG" ADD CONSTRAINT "PK_MFG_CODE" PRIMARY KEY  ( "MFG_CODE" ) USING 0;
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
