-- Database: GLOBALCIG Metadata version: 2 Exported: Mar 9, 2020
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5786_REFDESIG" USING 'GCG_5786_REFDESIG.mkd' PAGESIZE=4096 (
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0,
 "PARENT_BOM" CHAR(50),
 "PART" CHAR(50),
 "REF_DESIG" CHAR(50),
 "SEQ_BOM" CHAR(50) );
-- End Multi-Line Statement
ALTER TABLE "GCG_5786_REFDESIG" ADD CONSTRAINT "PK_ID" PRIMARY KEY  ( "ID" ) USING 0;
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
